--- #YAML:1.0
name:                News-Newsrc
version:             1.09
abstract:            Manages newsrc files
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Set::IntSpan:                  1.07
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steven McDougall (swmcd@world.std.com)
